version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6

jobs:
  test:
    docker:
      - image: circleci/node:14.15.1
    steps:
      - checkout
      - run: yarn
      - run:
          name: "Run Tests"
          command: yarn test

workflows:
  version: 2
  test:
    jobs:
      - test
