version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6

jobs:
  test:
    docker:
      - image: circleci/node:16.13.0
    steps:
      - checkout
      - run: yarn
      - run:
          name: "Run Tests"
          command: yarn test:unit

workflows:
  version: 2
  test:
    jobs:
      - test
