version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6

jobs:
  test:
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - run: yarn
      - run: yarn test
  lint:
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - run: yarn
      - run: yarn eslint:dryrun
      - run: yarn prettier:dryrun

workflows:
  version: 2
  test:
    jobs:
      - test
      - lint
